### ISSUE TITLE
add cpus to spladder

### ISSUE THREAD

**Issue by nttg8100** [ylab-hi/ScanNeo2#19]
When I ran spladder in the altsplicing task. It is lacked of parallel option that slows the process.
https://github.com/ylab-hi/ScanNeo2/blob/main/workflow/rules/altsplicing.smk#L17C1-L24C39
Just add `--parallel <cpus>`

**Comment by riasc** [comment]
Hey @nttg8100, 
Thanks for reporting this. I thought this only works for `test` mode. But this would make things a lot faster... Will change this these days.

Cheers

**Comment by riasc** [comment]
Resolved in #20 and ScanNeo2 v0.2.4

Thanks
