### ISSUE TITLE
Where I can download the required argument peptides

### ISSUE THREAD

**Issue by nttg8100** [ylab-hi/ScanNeo2#24]
I want to use the compile.py module.
However, in the repo, I can not found the description that illustrate where I can download the peptide.fasta
https://github.com/ylab-hi/ScanNeo2/blob/52a3818ec3189af502f18eba6b6a1a69b9b3a8c3/workflow/rules/prioritization.smk#L58C4-L58C43

**Comment by riasc** [comment]
Hi again,

do I understand you correctly you want to use it outside of the workflow? The peptide is basically the ensemble peptide sequence as defined here: https://github.com/ylab-hi/ScanNeo2/blob/52a3818ec3189af502f18eba6b6a1a69b9b3a8c3/workflow/rules/ref.smk#L20

**Comment by nttg8100** [comment]
Thank your for your support.
