### ISSUE TITLE
can i use targeted sequencing? rather than WES..

### ISSUE THREAD

**Issue by ilovegreentea** [ylab-hi/ScanNeo2#32]
Is it possible?
Can targeted sequencing data be input file?

we have WTS & targeted sequencing file..
please let me know can i use this...

Best,

**Comment by riasc** [comment]
Hi,
Thanks for asking this. Yes, the workflow should also work on WGS/WTS and any other targeting sequencing. However, depending on your interest, it will (currently) only consider coding regions and nothing outside of the exome. 

Best
